// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoETgog3N1Ui6mqXFKuI6KMk5oD3RVb9g',
    appId: '1:832388810759:android:451ac14347c7d2f29a82a2',
    messagingSenderId: '832388810759',
    projectId: 'fashion-app-9d056',
    storageBucket: 'fashion-app-9d056.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCegOXaShT0uWbTFhlm_7qSKD7LJkUOYno',
    appId: '1:832388810759:ios:83d43169222db1169a82a2',
    messagingSenderId: '832388810759',
    projectId: 'fashion-app-9d056',
    storageBucket: 'fashion-app-9d056.firebasestorage.app',
    iosBundleId: 'com.example.fashionApp',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5bs2IXlTd4lbt-CTbin9oxJRAzMTDLCE',
    appId: '1:832388810759:web:bbe007e254729a6c9a82a2',
    messagingSenderId: '832388810759',
    projectId: 'fashion-app-9d056',
    authDomain: 'fashion-app-9d056.firebaseapp.com',
    storageBucket: 'fashion-app-9d056.firebasestorage.app',
    measurementId: 'G-Z2KBBCX5M5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5bs2IXlTd4lbt-CTbin9oxJRAzMTDLCE',
    appId: '1:832388810759:web:071958ec6b85492d9a82a2',
    messagingSenderId: '832388810759',
    projectId: 'fashion-app-9d056',
    authDomain: 'fashion-app-9d056.firebaseapp.com',
    storageBucket: 'fashion-app-9d056.firebasestorage.app',
    measurementId: 'G-4E9DE3PGCH',
  );
}
